$handlerPath = "internal\handlers\product_handler.go"
$lines = Get-Content $handlerPath

$newFunc = @(
    "func GetProducts(c *gin.Context) {",
    "`tvar query models.ProductListQuery",
    "`tif err := c.ShouldBindQuery(&query); err != nil {",
    "`t`tc.JSON(http.StatusBadRequest, gin.H{`"error`": err.Error()})",
    "`t`treturn",
    "`t}",
    "",
    "`tif query.Page < 1 {",
    "`t`tquery.Page = 1",
    "`t}",
    "`tif query.Limit < 1 || query.Limit > 100 {",
    "`t`tquery.Limit = 20",
    "`t}",
    "",
    "`tinStockStr := `"any`"",
    "`tif query.InStock != nil {",
    "`t`tinStockStr = fmt.Sprintf(`"%v`", *query.InStock)",
    "`t}",
    "`tcacheKey := fmt.Sprintf(`"products:list:page=%d:limit=%d:search=%s:cat=%d:min=%.2f:max=%.2f:instock=%s:sort=%s`",",
    "`t`tquery.Page, query.Limit, query.Search, query.CategoryID, query.MinPrice, query.MaxPrice, inStockStr, query.Sort)",
    "",
    "`tvar cachedResponse models.ProductListResponse",
    "`tif found, _ := cache.Get(c.Request.Context(), cacheKey, &cachedResponse); found {",
    "`t`tc.JSON(http.StatusOK, cachedResponse)",
    "`t`treturn",
    "`t}",
    "",
    "`tdb := database.DB.Model(&models.Product{}).Preload(`"Category`").Preload(`"Inventories`")",
    "",
    "`t// Search by name or description",
    "`tif strings.TrimSpace(query.Search) != `"`" {",
    "`t`tlike := `"%`" + strings.TrimSpace(query.Search) + `"%`"",
    "`t`tdb = db.Where(`"name ILIKE ? OR description ILIKE ?`", like, like)",
    "`t}",
    "",
    "`t// Filter by category",
    "`tif query.CategoryID > 0 {",
    "`t`tdb = db.Where(`"category_id = ?`", query.CategoryID)",
    "`t}",
    "",
    "`t// Filter by price range",
    "`tif query.MinPrice > 0 {",
    "`t`tdb = db.Where(`"price >= ?`", query.MinPrice)",
    "`t}",
    "`tif query.MaxPrice > 0 {",
    "`t`tdb = db.Where(`"price <= ?`", query.MaxPrice)",
    "`t}",
    "",
    "`t// Filter by stock availability (joins inventory)",
    "`tif query.InStock != nil {",
    "`t`tdb = db.Joins(`"JOIN inventories ON inventories.product_id = products.id`").",
    "`t`t`tWhere(`"inventories.in_stock = ?`", *query.InStock)",
    "`t}",
    "",
    "`t// Count total before pagination",
    "`tvar total int64",
    "`tif err := db.Count(&total).Error; err != nil {",
    "`t`tc.JSON(http.StatusInternalServerError, gin.H{`"error`": `"Failed to count products`"})",
    "`t`treturn",
    "`t}",
    "",
    "`t// Sorting",
    "`tswitch query.Sort {",
    "`tcase `"price_asc`":",
    "`t`tdb = db.Order(`"price ASC`")",
    "`tcase `"price_desc`":",
    "`t`tdb = db.Order(`"price DESC`")",
    "`tcase `"name_asc`":",
    "`t`tdb = db.Order(`"name ASC`")",
    "`tcase `"name_desc`":",
    "`t`tdb = db.Order(`"name DESC`")",
    "`tcase `"newest`":",
    "`t`tdb = db.Order(`"created_at DESC`")",
    "`tdefault:",
    "`t`tdb = db.Order(`"created_at DESC`")",
    "`t}",
    "",
    "`t// Pagination",
    "`toffset := (query.Page - 1) * query.Limit",
    "`tvar products []models.Product",
    "`tif err := db.Offset(offset).Limit(query.Limit).Find(&products).Error; err != nil {",
    "`t`tc.JSON(http.StatusInternalServerError, gin.H{`"error`": `"Failed to fetch products`"})",
    "`t`treturn",
    "`t}",
    "",
    "`ttotalPages := int(math.Ceil(float64(total) / float64(query.Limit)))",
    "",
    "`tresponse := models.ProductListResponse{",
    "`t`tProducts:   products,",
    "`t`tPage:       query.Page,",
    "`t`tLimit:      query.Limit,",
    "`t`tTotal:      total,",
    "`t`tTotalPages: totalPages,",
    "`t}",
    "",
    "`t_ = cache.Set(c.Request.Context(), cacheKey, response, 3*time.Minute)",
    "`tc.JSON(http.StatusOK, response)",
    "}"
)

$before = $lines[0..16]
$after = $lines[99..($lines.Length - 1)]
$newLines = $before + $newFunc + $after

Set-Content -Path $handlerPath -Value $newLines -Encoding UTF8
