package models

import "time"

// CreditNote is issued against a sales Invoice when a customer return is
// approved (SRS 12.17). Currently only auto-generated by ApproveReturn -
// price-adjustment and post-sale-discount credit notes are a future
// extension of the same table/flow, not yet triggered anywhere.
type CreditNote struct {
ID               uint             `gorm:"primaryKey" json:"id"`
CreditNoteNumber string           `gorm:"uniqueIndex;not null" json:"credit_note_number"`
InvoiceID        uint             `gorm:"not null;index" json:"invoice_id"`
OrderID          uint             `gorm:"not null;index" json:"order_id"`
ReturnRequestID  *uint            `gorm:"index" json:"return_request_id,omitempty"`
CustomerName     string           `json:"customer_name"`
CustomerPhone    string           `json:"customer_phone"`
Reason           string           `json:"reason"`
TaxableAmount    float64          `json:"taxable_amount"`
CGSTAmount       float64          `json:"cgst_amount"`
SGSTAmount       float64          `json:"sgst_amount"`
IGSTAmount       float64          `json:"igst_amount"`
TotalAmount      float64          `json:"total_amount"`
IssuedAt         time.Time        `json:"issued_at"`
// CreatedByID is nil for system-generated notes (auto-issued on return
// approval) rather than a specific admin action.
CreatedByID *uint            `json:"created_by_id,omitempty"`
Items       []CreditNoteItem `gorm:"foreignKey:CreditNoteID" json:"items,omitempty"`
CreatedAt   time.Time        `json:"created_at"`
}

type CreditNoteItem struct {
ID           uint    `gorm:"primaryKey" json:"id"`
CreditNoteID uint    `gorm:"not null;index" json:"credit_note_id"`
ProductID    uint    `json:"product_id"`
ProductName  string  `json:"product_name"`
Quantity     int     `json:"quantity"`
Price        float64 `json:"price"`
GSTPercent   float64 `json:"gst_percent"`
GSTAmount    float64 `json:"gst_amount"`
}

// DebitNote is issued against a Vendor Bill for a purchase return, short
// supply, rate difference, or quality issue (SRS 12.18). Unlike CreditNote,
// this is always an explicit admin action - there is no automatic trigger
// on the purchase side comparable to a customer return.
type DebitNote struct {
ID              uint      `gorm:"primaryKey" json:"id"`
DebitNoteNumber string    `gorm:"uniqueIndex;not null" json:"debit_note_number"`
VendorBillID    uint      `gorm:"not null;index" json:"vendor_bill_id"`
VendorID        uint      `gorm:"not null;index" json:"vendor_id"`
Reason          string    `gorm:"not null" json:"reason"`
Amount          float64   `gorm:"not null" json:"amount"`
GSTAmount       float64   `gorm:"not null;default:0" json:"gst_amount"`
TotalAmount     float64   `json:"total_amount"`
IssuedAt        time.Time `json:"issued_at"`
CreatedByID     uint      `gorm:"not null" json:"created_by_id"`
CreatedAt       time.Time `json:"created_at"`
}

// DebitNoteRequest is the body for POST /admin/finance/vendor-bills/:id/debit-note
type DebitNoteRequest struct {
Amount    float64 `json:"amount" binding:"required,gt=0"`
GSTAmount float64 `json:"gst_amount"`
Reason    string  `json:"reason" binding:"required"`
}
