ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_otp_hash VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_otp_expires_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_otp_attempts INTEGER NOT NULL DEFAULT 0;
