ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS hold_status VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS hold_reason TEXT;
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS void_reason TEXT;
ALTER TABLE vendor_bills ADD COLUMN IF NOT EXISTS voided_by_id BIGINT NULL REFERENCES users(id);
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS void_reason TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS voided_by_id BIGINT NULL REFERENCES users(id);
